export const calculatorDataModel = {
  calculationNumber: '',
  department: undefined,
  commonValues: {
    packing: 'No',
    baseLoadingHours: '',
    baseUnloadingHourse: '',
    cubicFt: '',
    miles: '',
    driveTime: '',
    totalSmallBoxes: '',
    totalMediumBoxes: '',
    fragileBoxes: '',
    shuttle: false,
    liftGate: false,
    hardFloorCovers: false,
    filmFloorCovers: false,
    numOfExtraHeavyItem: '',
    extraStops: [],
  },
  dayPackingNoPacking: {
    name: 'Day - Packing / No packing',
    rate: '',
    moversToLoad: '',
    addMovers: '',
    removeMovers: '',
    moversToDrivesAndUnload: '',
    removeTrucks: '',
    noTwoTrips: false,
  },
}